### PR TITLE
Fixed PHPUnit\Framework\MockObject\Invocation usage in Matcher/* classes

### PR DESCRIPTION
**Pull request by zhem4ag**
Not all classes was correctly refactored for namespace usage

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
Can you please provide an example test case which does not work without this patch? Thanks!

**Comment by sebastianbergmann** [comment]
@zhem4ag Can you please answer my question? Thanks!

**Comment by zhem4ag** [comment]
Strange, I could reproduce only on single environment, but there exist conflict with phpunit installed separately in system.

Probably this PR in not needed, cause it works on other environments, where I checked.

**Comment by sebastianbergmann** [comment]
Thank you for your feedback. Please open a new issue and/or pull request if you are able to reproduce an issue.

**Comment by sebastianbergmann** [comment]
This could be the fix for #394.

**Comment by misyaath** [comment]
Perfect its works now Thank you so much

**Pull request merged**
