### PR TITLE
Add support for nullable typehinted variadic arguments

### PR DESCRIPTION
**Pull request by ruudk**
In a project we are using variadic arguments. In PHP 7.1 we now have the power of nullable type hints and return types. You can even do nullable typehinted variadic arguments like this:
```php
function send(?Message ...$messages) {
    foreach ($messages as $message) {
        if (null === $message) {
            continue;
        }

        // send 
    }
}

send(new Message(), null, new Message());
```

This works fine. But the mock does not understand the `?`. 

This PR adds support for it with a test in 10cdd64

It also adds a missing test for non-nullable type hinted variadic arguments in d857bf1.

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
Thank you!

**Comment by ruudk** [comment]
@sebastianbergmann Thanks for the fast merge! I know you already did a release today, but any chance to get a new one out with this awesomeness included 🙏 :D

**Comment by sebastianbergmann** [comment]
Tagged `4.0.4`.

**Comment by mamyn0va** [comment]
Hi !
Is it corrected in phpunit5 or only in newer releases?
I'm asking because I still have the issue on phpunit5.
Thanks a lot!

**Comment by sebastianbergmann** [comment]
PHPUnit 5.7 is no longer supported. Please open a new ticket in case this still applies to a supported version of PHPUnit.

**Comment by mamyn0va** [comment]
Ok, so I guess I will have to switch soon... thanks!

**Pull request merged**
