### PR TITLE
Make mocked method callable

### PR DESCRIPTION
**Pull request by sawmurai**
Make mocked methods of mocks for classes, that do not exist, callable.

### CODE REVIEW

**Comment by greg0ire** [comment]
Consider associating your ping247.de address so that GH can link these commits to your account.

**Comment by sawmurai** [comment]
Thanks for the hint. I'm not working for them anymore. I guess that I it must still be configured in my dev env. :)

**Comment by greg0ire** [comment]
> I guess that I it must still be configured in my dev env. 

Oh then you mean changing your email address? Yeah you can change it in your `.gitconfig` or by using `git config --global user.email youremail`

**Comment by sebastianbergmann** [comment]
Thanks!

**Comment by sawmurai** [comment]
@greg0ire Will do that :) thanks

**Pull request merged**
