### PR TITLE
Add support for void return types in generator

### PR DESCRIPTION
**Pull request by prolic**
resolves: https://github.com/sebastianbergmann/phpunit-mock-objects/issues/329

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
* "Add support for return types in generator" (the title of this pull request) is wrong; the generator has support for return types
* The title of #329 is more accurate; the generator is apparently missing support for the `void` return type introduced in PHP 7.1
* I don't believe, but would gladly be proven wrong, that the templates need to be updated to support the `void` return type; this pull requests seems to be much larger than should be required to add support for the `void` return type

**Comment by prolic** [comment]
About the template:

```
php > function foo() : void { echo 'foo'; }
php > function bar() : void { return foo(); }
PHP Fatal error:  A void function must not return a value in php shell code on line 1

Fatal error: A void function must not return a value in php shell code on line 1
```

And I updated the title of this PR.

**Comment by sebastianbergmann** [comment]
Of course, that makes sense; my bad.

It would be nice to get an error when trying to configure a return value for a method that has a `void` return type declaration. Do you want to look into this?

**Comment by prolic** [comment]
@sebastianbergmann I tried to, but it seems like this is not so easy possible. I don't know much about the internals. Feel free to submit a PR to my PR to improve this, I'm sure you spot it quickly.

**Comment by sebastianbergmann** [comment]
I'll try to work on this over the weekend, at least to get your PR merged.

**Pull request merged**
