### PR TITLE
try to fix __toString mocked method

### PR DESCRIPTION
**Pull request by remicollet**
Running composer test suite with PHPUnit 5.0.4 I encounter lot of failures

     1) Composer\Test\Downloader\DownloadManagerTest::testGetDownloaderForIncorrectlyInstalledPackage
     Failed asserting that exception of type "ErrorException" matches expected exception "InvalidArgumentException". Message was: "Method Mock_PackageInterface_a8c9deb9::__toString() must return a string value" at
     
     2) Composer\Test\Downloader\DownloadManagerTest::testBadPackageDownload
     Failed asserting that exception of type "ErrorException" matches expected exception "InvalidArgumentException". Message was: "Method Mock_PackageInterface_a8c9deb9::__toString() must return a string value" at
     
     3) Composer\Test\Downloader\DownloadManagerTest::testBadPackageDownloadWithSourcePreferred
     Failed asserting that exception of type "ErrorException" matches expected exception "InvalidArgumentException". Message was: "Method Mock_PackageInterface_a8c9deb9::__toString() must return a string value" at
     
     ....

This seems to fix this issue, but I'm obviously not a expert... just trying to point you to the place were the issue can be...

With this, composer test suite:

     PHPUnit 5.0.4 by Sebastian Bergmann and contributors.
    
     Runtime:       PHP 5.6.14 with Xdebug 2.3.3
     Configuration: /dev/shm/BUILD/composer-fcce52b169799fc5973d080d31c27532ca41b7b8/phpunit.xml.dist
     
     ...
     OK, but incomplete, skipped, or risky tests!
     Tests: 833, Assertions: 1636, Skipped: 2.

### CODE REVIEW

**Comment by remicollet** [comment]
I understand this solution will skip the "matchers" loop.

Perhaps better to set  $hasReturnValue =1
And in the loop 

                    if ($hasReturnValue<2) {
                        $returnValue    = $value;
                        $hasReturnValue = 2;
                    }

**Comment by sebastianbergmann** [comment]
I think this patch has the potential to hide real problems. Do you have a minimal, self-contained reproducing example?

**Comment by remicollet** [comment]
No sorry.... discovered in the composer test suite.... not "small"...

**Comment by remicollet** [comment]
This issue is fixed with latest PHPUnit 5.0.5

**Comment by danez** [comment]
We still have the same problem with 5.0.5. I open PR with a minimal test

**Pull request closed without merging**
