### PR TITLE
Fix mocking of interface which extend Throwable

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes https://github.com/sebastianbergmann/phpunit/issues/2995

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Issue reproduced in https://travis-ci.org/sebastianbergmann/phpunit-mock-objects/jobs/338651530

**Comment by DeepDiver1975** [comment]
@sebastianbergmann can I drag your attention to this PR? ;-) THX a lot!

**Comment by sebastianbergmann** [comment]
`Throwable` is not supposed to be implemented in userland (I know that PHP allows it, which is unfortunate). I am not convinced that it would be "good" for PHPUnit to support this.

That being said, can you elaborate why you implement `Throwable` in your code instead of extending `Exception`?

**Comment by DeepDiver1975** [comment]
> That being said, can you elaborate why you implement Throwable in your code instead of extending Exception?

We are trying to mock dbal's Doctrine\DBAL\Driver\DriverException which is an interface.
https://github.com/doctrine/dbal/blob/2.6/lib/Doctrine/DBAL/Driver/DriverException.php#L32

See https://github.com/owncloud/core/commit/1a5e9801a8a548a98c50f94d9b65a82ec87b6aa4 - in the workaround I switched to Doctrine\DBAL\Driver\AbstractDriverException

**Comment by DeepDiver1975** [comment]
FYI: Back in 2.5 the interface did not inherit from \Throwable - https://github.com/doctrine/dbal/blob/2.5/lib/Doctrine/DBAL/Driver/DriverException.php#L32

**Comment by sebastianbergmann** [comment]
@ocramius @beberlei Can you explain why Doctrine does this? Thanks!

**Comment by Ocramius** [comment]
Throwable is not implemented in userland, it is just implemented as part of `extends Exception`:

```php
interface SomeException extends Throwable // correct semantics, otherwise it can't be an exception anyway
{
}
```

```php
class MyException extends OutOfBoundsException implements SomeException
{
}
```

The change is just semantic.

From my PoV, it makes no sense to mock a `Throwable`, as a collaborator will unlikely ever be a `Throwable` .

What PHPUnit would have to do (if mocking is needed) is extending `Exception` in the mock when `Throwable` is detected as implemented interface.

**Comment by Ocramius** [comment]
> What PHPUnit would have to do (if mocking is needed) is extending `Exception` in the mock when `Throwable` is detected as implemented interface.

Ah, I see that this patch already does that :)

Also, re-thinking about the "makes no sense to mock a `Throwable`", it makes sense if the "auto-mocking on return types" kicks in on a `foo() : Throwable`

**Comment by sebastianbergmann** [comment]
Thank you for the explanation, @Ocramius.

**Comment by sebastianbergmann** [comment]
And thank you, @DeepDiver1975, for the patch! :-)

**Comment by DeepDiver1975** [comment]
> And thank you, @DeepDiver1975, for the patch! :-)

my pleasure - happy to contribute back to a tool we use for years!

**Pull request merged**
